### ISSUE TITLE
projectSettings(TAG)

### ISSUE THREAD

**Issue by mukko** [000ubird/Haxeon2#10]
- projectSettings.php  
  の移植。タグ機能は登録しかできていないため、他の機能の実装も必要

**Comment by 000ubird** [comment]
(^^ゞ

**Comment by mukko** [comment]
- [x] タグを登録する
- [x] 入力フォーム
- [ ] tagmapに登録
- [ ] tagになければ新規登録
- [ ] 登録を削除する
- [ ] プロジェクト編集時、Build+RunしてIDが変わった時に、tagmapに登録されているIDを新しいIDへ変更する

**Comment by mukko** [comment]
バリデーションが強力すぎる
tagにもtagmapにも登録されてない
