### ISSUE TITLE
プロジェクトの保存・非保存の修正

### ISSUE THREAD

**Issue by mukko** [000ubird/Haxeon2#139]
- 公開ボタン式にする
- 保存、未保存がわかりやすいUIにする

とか

**Comment by 000ubird** [comment]
・保存・非保存は1つの機能として残して、新しい機能としてプロジェクトの公開非公開設定を実装する方針。
・UIはSwitch式のボタンを使う予定。

**Comment by 000ubird** [comment]
所持しているプロジェクトに対しては、プロフィール内のプロジェクト一覧ページにて、プロジェクト設定内でも設定できるようにする。

**Comment by 000ubird** [comment]
データベースのプロジェクトテーブルの要素に【isPubic】を追加。
型はBoolean。
公開の場合はtrue、非公開の場合はfalse。

**Comment by 000ubird** [comment]
トップ画面のデイリーランキングとプロフィール内のプロジェクト表示ページの非公開プロジェクトの閲覧に関しては未実装なので実装する予定。

**Comment by 000ubird** [comment]
Linuxに移植したが、正しく動作しない。
原因を探している。

**Comment by 000ubird** [comment]
正しく動作しました。
