### ISSUE TITLE
任意のタイミングでフォークするように

### ISSUE THREAD

**Issue by mukko** [000ubird/Haxeon2#17]
- [ ] 他人のプロジェクトのページでBuild+Runする際にはDBの更新は行わない
- [ ] フォークボタンを押すと、自分のプロジェクトへフォークされる

**Comment by mukko** [comment]
- [ ] フォーク元を辿れるようにする

**Comment by 000ubird** [comment]
同名のプロジェクトの作成はできるように仕様変更

**Comment by 000ubird** [comment]
try-haxeのEditorクラス内で、ユーザーIDとプロジェクトIDからプロジェクト名を取得する

**Comment by 000ubird** [comment]
フォーク数カウンターに問題あり
